version: "3"
services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    restart: always
    container_name: php
    env_file: .env
    working_dir: /var/www/html
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/laravel.ini

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    working_dir: /var/www/html
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${APP_PORT}:80"

  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
volumes:
  db: